version: "3"
services:
  bot:
    env_file: ./.env
    image: angadsharma1016/chutkulabot
    deploy:
            replicas: 1

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Asia/Kolkata' #this is the time zone
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    deploy:
            replicas: 1


  spotify-download:
        image: angadsharma1016/spotify-download
        env_file: ./.env
        volumes:
                - ./Music:/app/Music
        deploy:
                replicas: 1
