version: '3'
services:
  spotify-download:
        image: angadsharma1016/spotify-download
        env_file: ./.env
        volumes:
                - /mnt/hdd/Music:/app/Music
        deploy:
                replicas: 1
