---
- name: update and upgrade
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 360

- name: install required packages
  apt:
    name: "{{  required_packages  }}"
    state: present

- name: install optional packages
  apt:
    name: "{{  optional_packages  }}"
    state: present

- name: install pip packages
  pip:
    name: "{{  pip_packages  }}"
    state: present

- name: user configuration
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    # TODO: password: ""
    groups: "{{ item.groups }}"
  loop:
    - { name: 'angad', groups: 'root' }
    - { name: 'angad', groups: 'docker' }
