---
- name: update and upgrade
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 360

- name: install required packages
  apt:
    name: "{{  required_packages  }}"
    state: present

- name: install optional packages
  apt:
    name: "{{  optional_packages  }}"
    state: present

- name: install pip packages
  pip:
    name: "{{  pip_packages  }}"
    state: present

- name: install docker
  shell:
    cmd: /usr/bin/curl -fsSL https://get.docker.com | /bin/bash
    creates: /usr/bin/docker

- name: ensure docker service is running
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - docker.service
    - containerd.service

- name: user configuration
  user:
    name: "{{ item.name }}"
    state: present
    shell: /bin/bash
    generate_ssh_key: yes
    password: "{{ user_password }}"
    groups: "{{ item.groups }}"
  loop:
    - { name: 'angad', groups: 'root' }
    - { name: 'angad', groups: 'docker' }

