# docker run -d -p 4443:4443 -p 443:443 -p 80:80 -v ncdata:/data --name nextcloudpi ownyourbits/nextcloudpi $DOMAIN
# if architecture is arm/v7 or armhf then run this ^
version: '3'

services:
  db:
    networks:
            - nextcloud
    env_file: ./.env
    image: mariadb
    ports:
            - 3306:3306
              # uncomment if not armhf
   #command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
     #- db:/var/lib/mysql
      - /mnt/hdd/nextcloud_db:/var/lib/mysql
    deploy:
            replicas: 1
    restart: always

  app:
    networks:
            - nextcloud
    image: nextcloud
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
        #- nextcloud:/var/www/html
        - /mnt/hdd/nextcloud_app:/var/www/html
    deploy:
            replicas: 1
    restart: always

networks:
        nextcloud:
