version: '3'

services:
  db:
    networks:
            - nextcloud
    env_file: ./.env
              # uncomment if not armhf
    image: lsioarmhf/mariadb #mariadb
    ports:
            - 3306:3306
              # uncomment if not armhf
   #command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
     #- db:/var/lib/mysql
      - /mnt/hdd/nextcloud_db:/var/lib/mysql
    deploy:
            replicas: 1

  app:
    networks:
            - nextcloud
    image: nextcloud
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
        #- nextcloud:/var/www/html
        - /mnt/hdd/nextcloud_app:/var/www/html
    deploy:
            replicas: 1

networks:
        nextcloud:
