version: '3'
services:
  pihole:
    container_name: pihole
    domainname: docker
    hostname: pihole
    image: pihole/pihole:latest
    env_file: ./.env
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      # - '67:67/udp'
      - '6969:80'
      - '443:443'
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/pihole/pihole:/etc/pihole
      # - ${USERDIR}/docker/pihole/pihole.log:/var/log/pihole.log
      - ${USERDIR}/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    environment:
      - DNS1=127.0.0.1
      - DNS2=1.1.1.1 # cloudflare DNS
    deploy:
            replicas: 1


